
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
using Luban;
using SimpleJSON;
using SerializationException = Luban.SerializationException;


namespace cfg
{
public sealed partial class Festival : Luban.BeanBase
{
    public Festival(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["fes_time"].IsNumber) { throw new SerializationException(); }  FesTime = _buf["fes_time"]; }
        { if(!_buf["fes_class"].IsNumber) { throw new SerializationException(); }  FesClass = _buf["fes_class"]; }
        { if(!_buf["fes_type"].IsNumber) { throw new SerializationException(); }  FesType = _buf["fes_type"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["game_desc"].IsString) { throw new SerializationException(); }  GameDesc = _buf["game_desc"]; }
        { var __json0 = _buf["fes_args1"]; if(!__json0.IsArray) { throw new SerializationException(); } FesArgs1 = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  FesArgs1.Add(__v0); }   }
        { var __json0 = _buf["fes_args2"]; if(!__json0.IsArray) { throw new SerializationException(); } FesArgs2 = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  FesArgs2.Add(__v0); }   }
        { var __json0 = _buf["score_reward"]; if(!__json0.IsArray) { throw new SerializationException(); } ScoreReward = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ScoreReward.Add(__v0); }   }
    }

    public static Festival DeserializeFestival(JSONNode _buf)
    {
        return new Festival(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 时间类型
    /// </summary>
    public readonly int FesTime;
    /// <summary>
    /// 活动所属
    /// </summary>
    public readonly int FesClass;
    /// <summary>
    /// 活动类型
    /// </summary>
    public readonly int FesType;
    /// <summary>
    /// 活动描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 游戏描述
    /// </summary>
    public readonly string GameDesc;
    /// <summary>
    /// 活动参数1
    /// </summary>
    public readonly System.Collections.Generic.List<int> FesArgs1;
    /// <summary>
    /// 活动参数2
    /// </summary>
    public readonly System.Collections.Generic.List<int> FesArgs2;
    /// <summary>
    /// 累计分数
    /// </summary>
    public readonly System.Collections.Generic.List<int> ScoreReward;
   
    public const int __ID__ = 288955800;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "fesTime:" + FesTime + ","
        + "fesClass:" + FesClass + ","
        + "fesType:" + FesType + ","
        + "desc:" + Desc + ","
        + "gameDesc:" + GameDesc + ","
        + "fesArgs1:" + Luban.StringUtil.CollectionToString(FesArgs1) + ","
        + "fesArgs2:" + Luban.StringUtil.CollectionToString(FesArgs2) + ","
        + "scoreReward:" + Luban.StringUtil.CollectionToString(ScoreReward) + ","
        + "}";
    }
}

}
