
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Pay : Luban.BeanBase
{
    public Pay(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["backgroud"].IsString) { throw new SerializationException(); }  Backgroud = _buf["backgroud"]; }
        { if(!_buf["good_type"].IsNumber) { throw new SerializationException(); }  GoodType = _buf["good_type"]; }
        { if(!_buf["pay_point"].IsString) { throw new SerializationException(); }  PayPoint = _buf["pay_point"]; }
        { if(!_buf["goodId"].IsNumber) { throw new SerializationException(); }  GoodId = _buf["goodId"]; }
        { if(!_buf["firstBuy"].IsNumber) { throw new SerializationException(); }  FirstBuy = _buf["firstBuy"]; }
        { if(!_buf["extraReward"].IsNumber) { throw new SerializationException(); }  ExtraReward = _buf["extraReward"]; }
        { if(!_buf["price"].IsNumber) { throw new SerializationException(); }  Price = _buf["price"]; }
    }

    public static Pay DeserializePay(JSONNode _buf)
    {
        return new Pay(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 商品图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 商品底板
    /// </summary>
    public readonly string Backgroud;
    /// <summary>
    /// 商品类型
    /// </summary>
    public readonly int GoodType;
    /// <summary>
    /// 计费点
    /// </summary>
    public readonly string PayPoint;
    /// <summary>
    /// 商品id
    /// </summary>
    public readonly int GoodId;
    /// <summary>
    /// 首充奖励
    /// </summary>
    public readonly int FirstBuy;
    /// <summary>
    /// 额外奖励
    /// </summary>
    public readonly int ExtraReward;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
   
    public const int __ID__ = 80008;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "backgroud:" + Backgroud + ","
        + "goodType:" + GoodType + ","
        + "payPoint:" + PayPoint + ","
        + "goodId:" + GoodId + ","
        + "firstBuy:" + FirstBuy + ","
        + "extraReward:" + ExtraReward + ","
        + "price:" + Price + ","
        + "}";
    }
}

}
