
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.pay
{
public partial class TbPay
{
    private readonly System.Collections.Generic.Dictionary<int, Pay> _dataMap;
    private readonly System.Collections.Generic.List<Pay> _dataList;
    
    public TbPay(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Pay>();
        _dataList = new System.Collections.Generic.List<Pay>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Pay _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Pay.DeserializePay(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Pay> DataMap => _dataMap;
    public System.Collections.Generic.List<Pay> DataList => _dataList;

    public Pay GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Pay Get(int key) => _dataMap[key];
    public Pay this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
