
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public item.TbItem TbItem {get; }
    public festival.TbFestival TbFestival {get; }
    public festivalIcon.TbFestivalIcon TbFestivalIcon {get; }
    public pay.TbPay TbPay {get; }
    public task.TbTask TbTask {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbFestival = new festival.TbFestival(loader("festival_tbfestival"));
        TbFestivalIcon = new festivalIcon.TbFestivalIcon(loader("festivalicon_tbfestivalicon"));
        TbPay = new pay.TbPay(loader("pay_tbpay"));
        TbTask = new task.TbTask(loader("task_tbtask"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbFestival.ResolveRef(this);
        TbFestivalIcon.ResolveRef(this);
        TbPay.ResolveRef(this);
        TbTask.ResolveRef(this);
    }
}

}
