
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Task : Luban.BeanBase
{
    public Task(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["refreshType"].IsNumber) { throw new SerializationException(); }  RefreshType = _buf["refreshType"]; }
        { if(!_buf["groupId"].IsNumber) { throw new SerializationException(); }  GroupId = _buf["groupId"]; }
        { if(!_buf["target"].IsNumber) { throw new SerializationException(); }  Target = _buf["target"]; }
        { if(!_buf["active"].IsNumber) { throw new SerializationException(); }  Active = _buf["active"]; }
        { if(!_buf["misc"].IsNumber) { throw new SerializationException(); }  Misc = _buf["misc"]; }
        { if(!_buf["value"].IsNumber) { throw new SerializationException(); }  Value = _buf["value"]; }
        { if(!_buf["reward"].IsNumber) { throw new SerializationException(); }  Reward = _buf["reward"]; }
    }

    public static Task DeserializeTask(JSONNode _buf)
    {
        return new Task(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 任务类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 刷新类型
    /// </summary>
    public readonly int RefreshType;
    /// <summary>
    /// 任务组
    /// </summary>
    public readonly int GroupId;
    /// <summary>
    /// 任务目标
    /// </summary>
    public readonly int Target;
    /// <summary>
    /// 参数操作类型
    /// </summary>
    public readonly int Active;
    /// <summary>
    /// 目标参数
    /// </summary>
    public readonly int Misc;
    /// <summary>
    /// 目标值
    /// </summary>
    public readonly int Value;
    /// <summary>
    /// 任务奖励
    /// </summary>
    public readonly int Reward;
   
    public const int __ID__ = 2599333;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "type:" + Type + ","
        + "refreshType:" + RefreshType + ","
        + "groupId:" + GroupId + ","
        + "target:" + Target + ","
        + "active:" + Active + ","
        + "misc:" + Misc + ","
        + "value:" + Value + ","
        + "reward:" + Reward + ","
        + "}";
    }
}

}
